### PR TITLE
Dev backend/anp 88 implement mailing funcionality on backend

### PR DESCRIPTION
**Pull request by FSostaric20**

### CODE REVIEW

**Review by nmidzic20 — CHANGES_REQUESTED** [review]
Migration issue fixed, receiving email with link works. Reset endpoint seems to be working fine by returning 400 Bad Request for an invalid token, can't test with valid token before Forgot password is implemented.
When testing Email endpoint, it works fine if the request contains email of an existing user, but throws 500 Server Error for a non-existent user mail, so it might be better to handle the error and return 400 Bad Request instead or similar.

**Comment by FSostaric20** [comment]
> can't test with valid token before Forgot password is implemented. 
The token generated is valid and can be tested by using the reset password endpoint with the code recieved in the email
>When testing Email endpoint, it works fine if the request contains email of an existing user, but throws 500 Server Error for a non-existent user mail, so it might be better to handle the error and return 400 Bad Request instead or similar.
The bug is fixed, the issue was with the function in the service that gets the user threw an exception if the user was not found

**Review by nmidzic20 — APPROVED** [review]
Tested with valid token too, server response is fixed. Everything works nicely

**Review by ssmrcek20 — APPROVED** [review]
Everything works

**Pull request merged**
