### PR TITLE
Dev backend/anp 33 statistics endpoints

### PR DESCRIPTION
**Pull request by HLuksic**
Created necessary endpoints for events, unit tests for adding and ending events fail but the methods do work in Swagger, fix should come after main story points are done.

### CODE REVIEW

**Review by ssmrcek20 — APPROVED** [review]
Looks good just don't forget to implement TODO features later

**Review by nmidzic20 — CHANGES_REQUESTED** [review]
Tests work in Swagger because `dbContext` relies on data from the Docker database, which has necessary initial data added from Migrations code. Unit tests have a different data source because they rely on fake database `context` created specifically for them, which requires adding necessary data in `Arrange` part before executing the `Act` part of the test. Some `Arrange` parts lack saving changes made to the test context, thus causing test to fail. After fixing this, individual tests should pass, though running all tests at once still causes one (`CreateEvent_GivenValidData_ShouldReturnSuccess`) to fail, probably due to improper `context` cleanup somewhere. In that case I suggest just changing both Card and Charger Id to 2 instead of 1.

**Comment by HLuksic** [comment]
> Tests work in Swagger because `dbContext` relies on data from the Docker database, which has necessary initial data added from Migrations code. Unit tests have a different data source because they rely on fake database `context` created specifically for them, which requires adding necessary data in `Arrange` part before executing the `Act` part of the test. Some `Arrange` parts lack saving changes made to the test context, thus causing test to fail. After fixing this, individual tests should pass, though running all tests at once still causes one (`CreateEvent_GivenValidData_ShouldReturnSuccess`) to fail, probably due to improper `context` cleanup somewhere. In that case I suggest just changing both Card and Charger Id to 2 instead of 1, in which case all tests pass at once.

Of course, done.

**Comment by HLuksic** [comment]
New issues arose due to changes to ChargerController, will fix later.

**Review by nmidzic20 — CHANGES_REQUESTED** [review]
Having `ChargerCreateRequest` makes sense for `AddCharger` method, not sure if it makes sense for `UpdateChargerByID` as well since `EventController` calls this method and needs to update `LastSync` property as well, which is available in `Charger` but not in `ChargerCreateRequest`. The same goes for the two tests that test Update method. The simplest way to resolve these issues seems to leave `ChargerCreateRequest` in `AddCharger` method, but to change it back to `Charger` in `UpdateChargerById`. Then in tests `UpdateCharger_GivenChargerDoesntExist_ShouldReturnError404` and `UpdateCharger_GivenChargerExists_ShouldReturnUpdatedCharger`, `ChargerCreateRequest` can be changed to `Charger` and  `LastSyncAt = DateTime.Now` added. Everything should then build properly, but if there is some stronger reason that necessitates having `ChargerCreateRequest` in Update method too, then ignore this suggestion and merge as soon as build issue is solved

**Comment by HLuksic** [comment]
Fixed like Noa suggested.

**Review by nmidzic20 — APPROVED** [review]
Everything builds properly, all unit tests pass

**Pull request merged**
