### PR TITLE
Dev backend/anp 34 charging station endpoints

### PR DESCRIPTION
**Pull request by HLuksic**
Implemented required endpoints for chargers, created MSTest unit test project and implemented tests for the endpoints.

### CODE REVIEW

**Review by nmidzic20 — APPROVED** [review]
Charger Controller is implemented with all methods. All methods are covered with unit tests using EF Core InMemory database for mock database, with clean instances of  DbContext to run the tests

**Review by ssmrcek20 — CHANGES_REQUESTED** [review]
Endpoints look good and everything is tested but you need to add .gitignore to Test project (you can copy .gitignore from backend folder) so bin and obj folders aren't pushed to git also for GET chargers and GET chargers byState you probably don't have to include Events

**Comment by HLuksic** [comment]
> Endpoints look good and everything is tested but you need to add .gitignore to Test project (you can copy .gitignore from backend folder) so bin and obj folders aren't pushed to git also for GET chargers and GET chargers byState you probably don't have to include Events

Done, .gitignore is added and untracked files removed

**Review by ssmrcek20 — APPROVED** [review]
Nice, .gitignore is added and now it can be merged to dev-backend.

**Pull request merged**
